import type { CVSection } from "@/types";

export const SAMPLE_CV_DATA: CVSection[] = [
  {
    id: 1,
    cv_id: 0,
    section_type: "personal_details",
    display_order: 0,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      full_name: "Alexandra Chen",
      title: "Senior Software Engineer",
      email: "alex.chen@email.com",
      phone: "+1 555 234 5678",
      location: "San Francisco, CA",
      nationality: "American",
      date_of_birth: "1995-07-21",
      gender: "Female",
      visa_status: "",
      driving_license: "",
      marital_status: "Single",
      religion: "",
      nic: "",
      photo_url: "/sample-avatar.png",
      photo_base64: "",
      links: [
        { id: "1", platform: "LinkedIn", url: "linkedin.com/in/alexchen" },
        { id: "2", platform: "GitHub", url: "github.com/alexchen" },
      ],
    },
  },
  {
    id: 2,
    cv_id: 0,
    section_type: "profile_summary",
    display_order: 1,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      summary:
        "<p>Results-driven Software Engineer with 6+ years of experience building scalable web applications and cloud-native systems. Passionate about clean code, system design, and delivering impactful products that serve millions of users.</p>",
    },
  },
  {
    id: 3,
    cv_id: 0,
    section_type: "experience",
    display_order: 2,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      entries: [
        {
          id: "e1",
          job_title: "Senior Software Engineer",
          employer: "TechCorp Inc",
          employer_link: "https://techcorp.com",
          location: "San Francisco, CA",
          start_date: "Jan 2022",
          end_date: "",
          current: true,
          description: "",
          bullets: [
            { text: "Led architecture of microservices platform handling 10M+ daily requests using Python and Kubernetes" },
            { text: "Reduced system latency by 40% through database optimization and Redis caching strategies" },
            { text: "Mentored team of 6 junior engineers and established engineering best practices" },
            { text: "Designed real-time data streaming pipeline processing 500K events per minute" },
          ],
        },
        {
          id: "e2",
          job_title: "Software Engineer",
          employer: "DataSystems Ltd",
          employer_link: "",
          location: "New York, NY",
          start_date: "Mar 2019",
          end_date: "Dec 2021",
          current: false,
          description: "",
          bullets: [
            { text: "Built scalable REST APIs in Node.js and TypeScript serving 2M+ active users" },
            { text: "Implemented CI/CD pipelines reducing deployment time from 2 hours to 15 minutes" },
            { text: "Led migration from monolithic to microservices architecture improving velocity by 60%" },
          ],
        },
      ],
    },
  },
  {
    id: 4,
    cv_id: 0,
    section_type: "education",
    display_order: 3,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      entries: [
        {
          id: "ed1",
          degree: "BSc Computer Science",
          institution: "Stanford University",
          institution_link: "",
          location: "Stanford, CA",
          start_date: "Sep 2015",
          end_date: "Jun 2019",
          score_type: "GPA",
          score_value: "3.8 / 4.0",
          description: "",
        },
      ],
    },
  },
  {
    id: 5,
    cv_id: 0,
    section_type: "skills",
    display_order: 4,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      entries: [
        { id: "s1", skill_name: "Python", level: "Advanced" },
        { id: "s2", skill_name: "TypeScript", level: "Advanced" },
        { id: "s3", skill_name: "React", level: "Intermediate" },
        { id: "s4", skill_name: "PostgreSQL", level: "Intermediate" },
        { id: "s5", skill_name: "Docker", level: "Intermediate" },
        { id: "s6", skill_name: "Kubernetes", level: "Intermediate" },
        { id: "s7", skill_name: "AWS", level: "Intermediate" },
        { id: "s8", skill_name: "Redis", level: "Intermediate" },
      ],
    },
  },
  {
    id: 6,
    cv_id: 0,
    section_type: "languages",
    display_order: 5,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      entries: [
        { id: "l1", language: "English", level: "Native" },
        { id: "l2", language: "Mandarin", level: "Professional" },
      ],
    },
  },
  {
    id: 7,
    cv_id: 0,
    section_type: "projects",
    display_order: 6,
    is_visible: true,
    created_at: "",
    updated_at: null,
    data: {
      entries: [
        {
          id: "p1",
          title: "Distributed Task Scheduler",
          subtitle: "Open Source Project",
          start_date: "2023",
          end_date: "Present",
          description:
            "<p>Built a fault-tolerant distributed task scheduling system supporting 100K+ concurrent jobs with priority queuing and real-time monitoring.</p>",
          link: "github.com/alexchen/scheduler",
          tech: ["Python", "Redis", "PostgreSQL", "React"],
        },
      ],
    },
  },
];
